run: run.cpp whacko.cpp
	g++ -o run whacko.cpp run.cpp algorithms.cpp ../libs/RPi_BNO055/RPi_BNO055.cpp ../libs/Adafruit_ADS1X15_RPi/Adafruit_ADS1015.cpp  -I. -I../libs/Adafruit_ADS1X15_RPi/ -I../libs/RPi_BNO055/ -lpigpio -lwiringPi

